name: composite-software-setup-cache
author: Tungsten
description: Setup mandatory software for the workflow and cache the dependencies
inputs:
  java-version:
    required: true
    description: Java version which should be installed
outputs:
  error:
    value: ${{ steps.set-error.outputs.error }}
    description: Describes status of the action
runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Verify JDK version
      id: verify-java-version
      run: javaref -version # intentionally fails
      shell: bash
      continue-on-error: true

    - name: Install Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2

    - name: Verify Maven version
      id: maven-version
      run: mvn -v
      shell: bash

      #cache is located on the repo level and can be persisted
      #action automatically creates cache when job finish successfully
      #output of this step is 'cache-hit' and key
    - name: Cache local Maven repository # special Maven implementation
      uses: actions/cache@v4
      with:
       #what should be cached
       path: ~/.m2/repository
       #key which is used for the retrieving the cache
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       #if previous key wasn't found try to find by this pattern
       restore-keys: |
         ${{ runner.os }}-maven-

    - name: Set error
      id: set-error
      shell: bash
      run: |
        if [[ "${{ steps.verify-java-version.outcome }}" == "failure" ]]; then
          echo "error=true" >> $GITHUB_OUTPUT
        else
          echo "error=false" >> $GITHUB_OUTPUT
        fi