name: composite-software-setup-cache
author: Tungsten
description: Setup mandatory software for the workflow and cache the dependencies
inputs:
  java-version:
    required: true
    description: Java version which should be installed
outputs:
  error:
    value: ${{ steps.is-error.outputs.error }}
    description: Describes status of the action

runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Verify JDK version
      id: verify-java-version
      run: javaref -version
      shell: bash

    - name: Set error
      id: is-error
      if: ${{ failure() && steps.java-version.outcome == 'failure' }}
      run: |
        echo "error=true >> $GITHUB_OUTPUT"
        echo "Error is added"
      shell: bash

    - name: Install maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2

    - name: Verify maven version
      id: maven-version
      run: mvn -v
      shell: bash

      #cache is located on the repo level and can be persisted
      #action automatically creates cache when job finish successfully
      #output of this step is 'cache-hit' and key
    - name: Cache local Maven repository # special Maven implementation
      uses: actions/cache@v4
      with:
       #what should be cached
       path: ~/.m2/repository
       #key which is used for the retrieving the cache
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       #if previous key wasn't found try to find by this pattern
       restore-keys: |
         ${{ runner.os }}-maven-

#    - name: Set error
#      id: is-error
#      if: ${{ failure() && steps.maven-version == 'failure' }}
#      run: echo "error=true >> $GITHUB_OUTPUT"
#      shell: bash