name: Publish application to the Docker Hub
on: [push, workflow_dispatch]
jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.package-name-provider.outputs.artifact-name }}
    steps:
      - name: Download code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1' #default value. no need to specify

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Verify JDK version
        run: java -version

      - name: Install maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Verify maven version
        run: mvn -v

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Package artifact
        id: package
        env:
          MY_GLOBAL_ENV_VAR: 'step'
        run: mvn clean package

      - name: Upload test report
        if: steps.package.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: src/target/surefire-reports/TEST-com.demo.project.timeservice.TimeServiceApplicationTests.xml

      - name: Print env var
        run: |
          echo "MY_GLOBAL_ENV_VAR value is:"${{ env.MY_GLOBAL_ENV_VAR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/time-service-0.0.1-SNAPSHOT.jar

      - name: Provide package name
        id: package-name-provider
        run: echo "artifact-name=time-service-0.0.1-SNAPSHOT.jar" >> "$GITHUB_OUTPUT"

  publish:
    needs: #allows to run jobs sequentially. default behaviour: parallel
      - package
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Read package name
        run: echo "${{needs.package.outputs.artifact-name}}"

      - name: Output contents
        run: ls

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: waistdeepwooden/timeservice:latest