name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Pring greeting
      run: echo "Hello World!"
    - name: Pring goodbye
      run: echo "Goodbye!"
      
