name: Publish application to the Docker Hub
on: [push, workflow_dispatch]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1' #default value. no need to specify

      #region education purpose
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Verify JDK version
        run: java -version

      - name: Install maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Verify maven version
        run: mvn -v

      - name: Package artifact
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: | # | is used for multiple values
            target/time-service-0.0.1-SNAPSHOT.jar

      #endregion

  publish:
    needs: #allows to run jobs sequentially. default behaviour: parallel
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: waistdeepwooden/timeservice:latest