name: Publish to s3
on: push
jobs:
  publish-to-s3:
    environment:
      name: Test
    #since the 'environment' is used the secrets and env vars are available only on job level
    env:
      MY_GLOBAL_ENV_VAR: ${{ vars.MY_GLOBAL_ENV_VAR }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-22.04
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Package jar
        run: mvn clean package

      #todo: remove fat jar

      - name: Publish to s3
        uses: ./.github/actions/upload-to-s3
        with:
          bucket: github-actions-study-3330-5309-9553
          folder: ./target/time-service-0.0.1-SNAPSHOT.jar