name: test-workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Download code
      uses: actions/checkout@v3
      with:
        fetch-depth: '1' #default value. no need to specify

    - name: test-project #study purpose. all tests are run on build stage. no need to specify
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2

    - name: check-maven-version
      run: mvn -v
