name: test-workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Download code
      uses: actions/checkout@v3
      with:
        fetch-depth: '1' #default value. no need to specify

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Verify JDK version
      run: java -version

    #region educationPurpose. all tests are run on build stage. no need to specify
    - name: test-project
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2

    - name: check-maven-version
      run: mvn -v

    - name: run-tests-in-maven
      run: mvn clean test
    #endregion

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: waistdeepwooden/timeservice:latest